/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:126f8d78-55b9-46e9-a4b2-ee5a2198fa6e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MlRbfPcvO",
    "aws_user_pools_web_client_id": "6nqhl0ck17fvuue78qrhf9msbt",
    "oauth": {},
    "aws_user_files_s3_bucket": "psab-documents225914-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
